## title: Minimal theme
title: HRISHIKESH ANAND
## logo: /assets/img/logo.png
logo: Images/HA_DP_.png
theme: jekyll-theme-minimal
## description: Minimal is a theme for GitHub Pages.
description: DATA [Cleaning, Analyzing, Summarizing, Visualizing]
## show_downloads: true
## google_analytics:
